### ISSUE TITLE
Add option to start in fullscreen

### ISSUE THREAD

**Issue by bhajneet** [ShabadOS/desktop#275] opened 2019-11-04 14:46 UTC
_Related to https://github.com/ShabadOS/desktop/issues/40 by @Harjot1Singh_

This along with 40 would allow gurdwaras to start up in fullscreen automatically on boot

**Comment by Harjot1Singh** [comment] 2019-11-15 00:59
Duplicate of #18

**Closed by Harjot1Singh** 2019-11-15 00:59 UTC
Labels: Priority: Medium, Status: Confirmed, Type: Feature
