### ISSUE TITLE
disable screen power & sleep when in full screen

### ISSUE THREAD

**Issue by bhajneet** [ShabadOS/desktop#309] opened 2019-11-16 00:40 UTC
the screen should not turn off / the pc should not go to sleep on windows if shabad os is in fullscreen, similar to how videos in fullscreen work. not sure of what is the case on mac os.

**Comment by Harjot1Singh** [comment] 2020-02-27 21:54
Duplicate of #357

**Closed by Harjot1Singh** 2020-02-27 21:54 UTC
Labels: Priority: 2 Medium, Status: Confirmed, Type: Feature/Enhancement
