### ISSUE TITLE
Implement better bookmarks

### ISSUE THREAD

**Issue by Harjot1Singh** [ShabadOS/desktop#20] opened 2017-12-26 21:09 UTC
How would one use this for an Akhand Paath? Couldn't seem to find anything relating to this, nor figure out what the Akhand Paath View does.

**Comment by bhajneet** [comment] 2017-12-27 21:42
Akhand Paath View is supposed to make it so that when you are at the end of a shabad and press the down key or are at the beginning of a shabad and press the up key it should go to the next or previous shabad, respectively. It is set as an option so some people aren't caught by surprise when the shabad is changed so easily. (Otherwise you would use the ctrl+{Up,Down} to change the shabad.) Basically, it is to make it so you can keep pressing down over and over again to go through every single shabad. This will be helpful in the future when we incorporate using a powerpoint/keynote clicker to change lines as well.

Perhaps we can change the name to "Akhand Path Mode" instead of "View" to reduce confusion.

**Comment by Harjot1Singh** [comment] 2017-12-27 22:10
I see. If I was to use this for an Akhand Paath, what would be the procedure? Could we add some documentation? I really like this project, and would love to see this in Gurdwaras more!

**Comment by bhajneet** [comment] 2017-12-27 22:29
Well if you were using this for an Akhand Paath, it would only be to ease usage since you only have to hit the down key over and over (and over and over) again. If Akhand Paath mode was disabled, you would have to use the ctrl+down arrow shortcut. So you could do an Akhand Path either way, one would just be easier since you don't have to watch out for last lines or anything.

Documentation would be great. Using Shabad OS in more gurdwaras would be even greater!

**Comment by Harjot1Singh** [comment] 2017-12-27 22:38
Makes sense. The only confusion for me was that I couldn't figure out how to get this to work with an Akhand Paath/how to start it alongside an Akhand Paath, since it doesn't work when you reach the end of Japji Sahib, and you have to search for the beginning of SGGS to start it from there.

I suspect it would help Gurdwara uptake if these sorts of things were documented, would be happy to contribute to this as well, I suspect in the `website` repo?

**Comment by bhajneet** [comment] 2017-12-27 23:47
I can understand your confusion, esp if you went in from the bookmarks section. We had not thought of that scenario. 

If we removed the option in Settings and made it a bookmark it would mean we need a different way to find the current line / page if starting at any other point other than the beginning of an Akhand Paath.

Another idea is instead to leave the option as is, but re-name to something that means you can go to next and previous shabads using just the up and down key in addition to the ctrl shortcut and add a bookmark as "Akhand Paath" which is actually just the first shabad (mool mantar only in the database I believe). 

Or perhaps to re-think how we are setting up all our banis and allow people to "leave" japji sahib at the last line. Whether that should take them to the rehraas as in akhand paath or to the next bani in nitnem, idk how to reconcile.

Have to think through this a little more.

Documentation is a great idea, please do not contribute in the website repo just yet. Adding our documentation to the website is a good idea too, but perhaps there is another option of just using our github documentation pages as these repo's have a wiki as well. Any thoughts on which you prefer and why?

**Comment by Harjot1Singh** [comment] 2017-12-28 02:19
Agreed, I think this should be opened up further and mapped out properly.

GH pages for documentation; it's pretty, and you have the option of generating documentation from comments if so desired in the future.

**Comment by Harjot1Singh** [comment] 2018-01-22 01:39
Thinking about this again, should this mode not be the default behaviour? Are there any major downsides of having this by default, and not presenting the option, avoiding clutter?

**Comment by bhajneet** [comment] 2018-01-23 13:39
We don't want people to accidentally change the shabad and then be confused about how to get back. One idea of ours was to not allow change on down-arrow-held unless there was a separate down-arrow press on the last line specifically. But even that caused some confusion.

An option I can think of is to append a faux-line to each shabad that says "Go to next shabad". This line could be activated for GUI heavy users (And also creates an option for mouse-only users, since there is currently no way for them to do this).

On avoiding clutter, we should have different menus in the settings page, it can't just be one long page anymore. One other idea is to change the menu icon to not load a new page, but to pop-up a system menu which is simply a bunch of toggles. This is a benefit in the scenario that someone wants to change settings while inside a shabad. Instead of having to juggle navigation arrows and worrying about not activating the line-being-sung it is much easier to keep them both available at the same time.

**Comment by Harjot1Singh** [comment] 2018-01-23 13:59
I agree. Change the menu icon to a settings icon, and then pop out is the way forward. Able to create an  issue?

**Comment by Harjot1Singh** [comment] 2018-01-23 14:00
We can think about the points regarding the next shabad in more detail once we've completed Q1?

**Comment by bhajneet** [comment] 2018-01-23 14:06
If we change the menu icon to a settings icon, what will happen to things like "Live Captions Tool" and "Connect to..." menus? Could move them to a different icon, but I prefer to keep the controller clean (It already looks cluttered to some new users).

We can talk about "next shabad" after Q1

**Comment by Harjot1Singh** [comment] 2018-01-23 14:11
Oh, I forgot how the current menu looks - it already has settings. I agree.

**Comment by bhajneet** [comment] 2019-04-03 15:58
Based on the discussion above and over the year, it seems that there should be a way to do a couple things:

- Folder bookmarks (so "nitnem" as folder and various banis inside, navigating to end of line and beyond would take you to next "bookmark" inside this folder)
- Dynamic bookmarks (a way to keep a "pointer" so your reading progress is saved, i.e. you're reading sehaj paath and whichever last shabad you opened is the result of the dynamic bookmark, so it's always up to date with your reading progress)
- Akhand paath starting bookmark (a way to simple start an akhand paath so that all further navigation beyond current shabad simply takes you to the successive shabad all the way to the end of the source's shabad list)

**Comment by bhajneet** [comment] 2019-04-25 19:04
Asa Di Vaar and other larger banis should also be split up into a folder

**Comment by bhajneet** [comment] 2020-03-22 19:41
To be broken up into separate issues

**Comment by bhajneet** [comment] 2020-07-06 00:40
Duplicate of #483

**Closed by bhajneet** 2020-07-06 00:40 UTC
Labels: Effort: 109 pts, Impact: Avg, Status: ? ? ?, Type: Feat
