### ISSUE TITLE
Slider number are getting covered by title bar

### ISSUE THREAD

**Issue by saihaj** [ShabadOS/desktop#556] opened 2020-05-25 17:28 UTC
**Describe the bug**
If the slider is the first option then the numbers shown while sliding get covered by title bar of that option menu.

**To Reproduce**
1. Go to 'Settings'
2. Click on 'Layout'
3. Use the 'Font Size' slider 
4. See that the number on slider gets covered by top panel

**Expected behavior**
The numbers should not be covered by title bar.

**Screenshots**
<img width="912" alt="image" src="https://user-images.githubusercontent.com/44710980/82833145-da157d80-9e82-11ea-8b31-1e512b31c5fa.png">

![IMG_1036](https://user-images.githubusercontent.com/44710980/82833151-dc77d780-9e82-11ea-884e-89a5b2e76e8c.jpg)

**Specs**
 - Device: MacBook Pro and iPhone 11
 - OS: Mac OS 10.15.4 and iOS 13.3.1
 - Browser Firefox,  iOS Safari
 - ShabadOS version: 2.7.0
 - ShabadOS database version: 4.7.0
 - Architecture: x64

**Additional context**
Same issue with 'Display' > 'Previous Lines'

**Comment by bhajneet** [comment] 2020-05-25 17:35
Duplicate

**Comment by bhajneet** [comment] 2020-05-26 15:18
Duplicate of #516

**Closed by bhajneet** 2020-05-26 15:18 UTC
Labels: Status: ? ? ?, Type: Fix
